#include "src/game/envfx_snow.h"

const GeoLayout pss_area_0_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, pss_dl_a_main_room_geo),
			GEO_BRANCH(1, pss_dl_a_main2room_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2351, -5693, -95),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-10000, 20000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, pss_dl_a_avisualMiddle_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pss_dl_a_main_room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -7327, -6031, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2725, 10300, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, pss_dl_a_main_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(5, 11327, -6, -100, pss_dl_dehwater_001_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pss_dl_a_main2room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 4000, -6037, -100),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-10000, 20000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, pss_dl_a__dehwater_mesh_layer_5),
				GEO_DISPLAY_LIST(1, pss_dl_a__dehwater_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 594, 3000, 0),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-10000, 20000),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_update_fog),
					GEO_DISPLAY_LIST(1, pss_dl_a_main_bottom_pillars_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 991, 7000, 0),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-10000, 20000),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_update_fog),
					GEO_DISPLAY_LIST(1, pss_dl_a_main_top_pillars_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 771, 5505, 0),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-10000, 20000),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_update_fog),
					GEO_DISPLAY_LIST(1, pss_dl_a_main2_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 991, 5788, 400),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-10000, 20000),
				GEO_OPEN_NODE(),
					GEO_ASM(5, geo_update_fog),
					GEO_DISPLAY_LIST(5, pss_dl_a_main2_001_mesh_layer_5),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 3734, 7851, 7),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-10000, 20000),
				GEO_OPEN_NODE(),
					GEO_ASM(4, geo_update_fog),
					GEO_DISPLAY_LIST(4, pss_dl_a_main2_002_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 771, 5505, 0),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-10000, 20000),
				GEO_OPEN_NODE(),
					GEO_ASM(6, geo_update_fog),
					GEO_DISPLAY_LIST(5, pss_dl_a_main2_003_mesh_layer_5),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pss_area_0[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_backdrop_move),
					GEO_TRANSLATE_ROTATE_WITH_DL(0, 0, 0, 0, 0, 0, 0, sky_dome_sky_dome_001_mesh_2),
					GEO_DISPLAY_LIST(0, sky_dome_material_revert_render_settings2),
					GEO_BRANCH(1, pss_area_0_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_WATER, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, pss_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, pss_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, pss_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
