#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(4, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, castle_grounds_dl_aa_ROOM1_geo),
			GEO_BRANCH(1, castle_grounds_dl_aa_ROOM1_2_green_geo),
			GEO_BRANCH(1, castle_grounds_dl_aa_ROOM2_geo),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, castle_grounds_dl_shared_hallway_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_dl_aa_ROOM1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1088, -183, 0),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-3000, 4500),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_a_entry_pillars_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 3500, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_fog),
			GEO_DISPLAY_LIST(1, castle_grounds_dl_a_fancy_wall_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 11000, 0, 0),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-9000, 9000),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_a_PILLARROOM_003_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 12769, -5333, 0),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2000, 2000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_a_ROOM_transfer_to_green_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1043, -381, 0),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-5000, 5000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, castle_grounds_dl_awaters_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 12485, -1100, -101),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-10000, 10000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, castle_grounds_dl_awaters_001_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 12764, -5041, 10),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2000, 2000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, castle_grounds_dl_awaters_002_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 12485, -1100, -101),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-10000, 10000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, castle_grounds_dl_awaters_005_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 3500, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_azROOM_002_mesh),
			GEO_DISPLAY_LIST(1, castle_grounds_dl_azROOM_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4900, 200, 0),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-3000, 7100),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_azROOM_003_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 13500, 0, 0),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-9000, 10000),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_azzROOM_001_mesh),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_azzROOM_001_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 8932, -5684, 0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_dl_aa_ROOM1_2_green_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 9000, -5500, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_fog),
			GEO_DISPLAY_LIST(1, castle_grounds_dl_a_aROOM_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 9267, -5487, 357, castle_grounds_dl_a_ROOM_prev_room_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 9000, -5500, 0, castle_grounds_dl_a_ROOM_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, 9421, -7600, 294, castle_grounds_dl_awaters_green_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(5, 12764, -5041, 10, castle_grounds_dl_awaters_004_mesh_layer_5),
		GEO_ASM(5, geo_update_fog),
		GEO_DISPLAY_LIST(5, castle_grounds_dl_natty_moss_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_dl_aa_ROOM2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -194, -4123, 7870),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_fog),
			GEO_DISPLAY_LIST(1, castle_grounds_dl_a__SLIDE_Room_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2113, -3803, 8049, castle_grounds_dl_a__SLIDE_Room_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2113, -3803, 8049, castle_grounds_dl_a__SLIDE_Room_003_mesh_layer_1),
		GEO_ASM(5, geo_update_fog),
		GEO_DISPLAY_LIST(5, castle_grounds_dl_a_ROOM_plantz_mesh_layer_5),
		GEO_ASM(4, geo_update_fog),
		GEO_DISPLAY_LIST(4, castle_grounds_dl_a_ROOM_plantz_001_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(5, -1300, -6400, 9100, castle_grounds_dl_awaters_003_mesh_layer_5),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -309, -801, 8056),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_WATER, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, castle_grounds_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
