extern const GeoLayout beam_geo[];
extern Lights1 beam_inner_beam_layer5_lights;
extern u8 beam_water_big_chungus__ia4[];
extern u8 beam_water_sitting_clear_ia8[];
extern Vtx beam_beam_mesh_layer_5_vtx_0[89];
extern Gfx beam_beam_mesh_layer_5_tri_0[];
extern Gfx mat_beam_inner_beam_layer5[];
extern Gfx mat_revert_beam_inner_beam_layer5[];
extern Gfx beam_beam_mesh_layer_5[];
extern Gfx beam_material_revert_render_settings[];
