extern const GeoLayout parasite_geo[];
extern Lights1 parasite_hazy_lights;
extern u8 parasite_orb_ci8[];
extern u8 parasite_orb_ci8_pal_rgba16[];
extern Vtx parasite_2egg_mesh_layer_5_vtx_0[32];
extern Gfx parasite_2egg_mesh_layer_5_tri_0[];
extern Vtx parasite_haze_mesh_layer_5_vtx_0[9];
extern Gfx parasite_haze_mesh_layer_5_tri_0[];
extern Gfx mat_parasite_egg_v4[];
extern Gfx mat_revert_parasite_egg_v4[];
extern Gfx mat_parasite_hazy[];
extern Gfx mat_revert_parasite_hazy[];
extern Gfx parasite_2egg_mesh_layer_5[];
extern Gfx parasite_haze_mesh_layer_5[];
extern Gfx parasite_material_revert_render_settings[];
