extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_sm64_material_lights;
extern u8 castle_grounds_dl_Cliff_2_ci8[];
extern u8 castle_grounds_dl_Cliff_2_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_Cube_001_mesh_vtx_0[84];
extern Gfx castle_grounds_dl_Cube_001_mesh_tri_0[];
extern Gfx mat_castle_grounds_dl_sm64_material[];
extern Gfx mat_revert_castle_grounds_dl_sm64_material[];
extern Gfx castle_grounds_dl_Cube_001_mesh[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
