extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_sm64_material_layer1_area1_lights;
extern Lights1 castle_grounds_dl_water_layer5_area1_lights;
extern u8 castle_grounds_dl_Cliff_2_rgba16[];
extern u8 castle_grounds_dl_water_sitting_transparent_ia16[];
extern u8 castle_grounds_dl_water_smooth_ia16[];
extern Vtx castle_grounds_dl_Cube_001_mesh_vtx_0[134];
extern Gfx castle_grounds_dl_Cube_001_mesh_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_sm64_material_layer1_area1[];
extern Gfx mat_revert_castle_grounds_dl_sm64_material_layer1_area1[];
extern Gfx mat_castle_grounds_dl_water_layer5_area1[];
extern Gfx mat_revert_castle_grounds_dl_water_layer5_area1[];
extern Gfx castle_grounds_dl_Cube_001_mesh[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_5[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
