#include "src/game/envfx_snow.h"

const GeoLayout big_orb_geo[] = {
	GEO_CULLING_RADIUS(850),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 135, 65),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 98304),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -25, 0, 0, 90, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(21, geo_trippy_lookat),
								GEO_ASM(0, geo_update_layer_transparency),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, big_orb_big_orb_orb_mesh_layer_5),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_TRANSPARENT, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, big_orb_big_orb_haze_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, big_orb_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
