extern const GeoLayout squat_palm_geo[];
extern Lights1 squat_palm_f3d_material_layer1_lights;
extern Lights1 squat_palm_leafs_layer1_lights;
extern u8 squat_palm_bark_palm_i8[];
extern Vtx squat_palm_squat_palm_mesh_layer_1_vtx_0[11];
extern Gfx squat_palm_squat_palm_mesh_layer_1_tri_0[];
extern Vtx squat_palm_squat_palm_mesh_layer_1_vtx_1[81];
extern Gfx squat_palm_squat_palm_mesh_layer_1_tri_1[];
extern Gfx mat_squat_palm_f3d_material_layer1[];
extern Gfx mat_revert_squat_palm_f3d_material_layer1[];
extern Gfx mat_squat_palm_leafs_layer1[];
extern Gfx mat_revert_squat_palm_leafs_layer1[];
extern Gfx squat_palm_squat_palm_mesh_layer_1[];
extern Gfx squat_palm_material_revert_render_settings[];
