extern const GeoLayout pss_area_0_geo[];
extern const GeoLayout pss_dl_a_main_room_geo[];
extern const GeoLayout pss_dl_a_main2room_geo[];
extern const GeoLayout pss_area_0[];
extern const Collision pss_area_0_collision[];
extern const u8 pss_area_0_collision_rooms[];
extern const MacroObject pss_area_0_macro_objs[];
extern Lights1 pss_dl_waterg_layer5_lights;
extern u8 pss_dl_dirt_true_i8[];
extern u8 pss_dl_ceiling1_i8[];
extern u8 pss_dl_marble_2_i8[];
extern u8 pss_dl_temple_mandella_i8[];
extern u8 pss_dl_water_pls_try_sharper_ia4[];
extern u8 pss_dl_water_big_chungus_defined_ia4[];
extern u8 pss_dl_best_stone_small_i8[];
extern u8 pss_dl_tile__i8[];
extern Vtx pss_dl_a_avisualMiddle_mesh_layer_1_vtx_0[12];
extern Gfx pss_dl_a_avisualMiddle_mesh_layer_1_tri_0[];
extern Vtx pss_dl_a_main_mesh_layer_1_vtx_0[102];
extern Gfx pss_dl_a_main_mesh_layer_1_tri_0[];
extern Vtx pss_dl_a_main_mesh_layer_1_vtx_1[53];
extern Gfx pss_dl_a_main_mesh_layer_1_tri_1[];
extern Vtx pss_dl_a_main_mesh_layer_1_vtx_2[20];
extern Gfx pss_dl_a_main_mesh_layer_1_tri_2[];
extern Vtx pss_dl_a_main_mesh_layer_1_vtx_3[57];
extern Gfx pss_dl_a_main_mesh_layer_1_tri_3[];
extern Vtx pss_dl_dehwater_001_mesh_layer_5_vtx_0[7];
extern Gfx pss_dl_dehwater_001_mesh_layer_5_tri_0[];
extern Vtx pss_dl_a_main2_mesh_layer_1_vtx_0[150];
extern Gfx pss_dl_a_main2_mesh_layer_1_tri_0[];
extern Vtx pss_dl_a_main2_mesh_layer_1_vtx_1[354];
extern Gfx pss_dl_a_main2_mesh_layer_1_tri_1[];
extern Vtx pss_dl_a_main2_mesh_layer_1_vtx_2[23];
extern Gfx pss_dl_a_main2_mesh_layer_1_tri_2[];
extern Vtx pss_dl_a_main2_mesh_layer_1_vtx_3[121];
extern Gfx pss_dl_a_main2_mesh_layer_1_tri_3[];
extern Vtx pss_dl_a_main2_mesh_layer_1_vtx_4[16];
extern Gfx pss_dl_a_main2_mesh_layer_1_tri_4[];
extern Vtx pss_dl_dehwater_mesh_layer_5_vtx_0[73];
extern Gfx pss_dl_dehwater_mesh_layer_5_tri_0[];
extern Gfx mat_pss_dl_dirt_layer1[];
extern Gfx mat_revert_pss_dl_dirt_layer1[];
extern Gfx mat_pss_dl_mandela_1_vtx_layer1[];
extern Gfx mat_revert_pss_dl_mandela_1_vtx_layer1[];
extern Gfx mat_pss_dl_black_marble_vtx_layer1[];
extern Gfx mat_revert_pss_dl_black_marble_vtx_layer1[];
extern Gfx mat_pss_dl_pool_bottom_vtx_layer1[];
extern Gfx mat_revert_pss_dl_pool_bottom_vtx_layer1[];
extern Gfx mat_pss_dl_white_marble_vtx_layer1[];
extern Gfx mat_revert_pss_dl_white_marble_vtx_layer1[];
extern Gfx mat_pss_dl_waterg_layer5[];
extern Gfx mat_revert_pss_dl_waterg_layer5[];
extern Gfx mat_pss_dl_stones_layer1[];
extern Gfx mat_revert_pss_dl_stones_layer1[];
extern Gfx mat_pss_dl_carved_area_layer1[];
extern Gfx mat_revert_pss_dl_carved_area_layer1[];
extern Gfx pss_dl_a_avisualMiddle_mesh_layer_1[];
extern Gfx pss_dl_a_main_mesh_layer_1[];
extern Gfx pss_dl_dehwater_001_mesh_layer_5[];
extern Gfx pss_dl_a_main2_mesh_layer_1[];
extern Gfx pss_dl_dehwater_mesh_layer_5[];
extern Gfx pss_dl_material_revert_render_settings[];
