#include "levels/pss/area_0/collision.inc.c"
#include "levels/pss/area_0/room.inc.c"
#include "levels/pss/area_0/macro.inc.c"
#include "levels/pss/area_0/spline.inc.c"
#include "levels/pss/model.inc.c"
